services:
  fastapi:
    build: .
    container_name: fastapi-invoices-app
    ports:
      - "8000:8000"
    volumes:
      - .:/invoices
      - ./db:/db
    environment:
      - PYTHONUNBUFFERED=1
